# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0004_auto_20170331_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinkingenvuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('expert', 'Expert')], default='user', max_length=255),
        ),
    ]
