# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0006_infographic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infographic',
            name='title',
        ),
        migrations.AlterField(
            model_name='infographic',
            name='image',
            field=models.ImageField(upload_to='infographics/'),
        ),
    ]
