# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0007_auto_20170331_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographic',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
