# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0009_auto_20170401_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=255)),
                ('answer', models.CharField(default='', max_length=255)),
                ('replier', models.IntegerField(default=0)),
                ('open_to_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.ThinkingEnvUser')),
            ],
        ),
    ]
