# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0012_ticket_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=255)),
                ('is_request_direct', models.BooleanField(default=False)),
                ('requesting_authority_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('trainees_count', models.IntegerField()),
                ('trainees_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('director_phone_number', models.CharField(max_length=255)),
                ('director_email', models.CharField(max_length=255)),
                ('day', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('is_room_available', models.BooleanField(default=False)),
                ('about_us', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.ThinkingEnvUser')),
            ],
        ),
    ]
