# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0013_workshoprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoprequest',
            old_name='is_request_direct',
            new_name='is_workshop_direct',
        ),
    ]
