# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0015_auto_20170404_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprequest',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
