# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0016_auto_20170404_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
