# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0018_auto_20170405_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.ThinkingEnvUser')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.Workshop')),
            ],
        ),
    ]
