# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0020_auto_20170405_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshopregistration',
            unique_together=set([('user', 'workshop')]),
        ),
    ]
