# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0021_auto_20170406_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
