# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0022_auto_20170406_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprequest',
            name='about_us_other_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workshoprequest',
            name='about_us',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('training_team', 'Training Team'), ('people', 'People'), ('other', 'Other')], max_length=255),
        ),
    ]
