# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0023_auto_20170411_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoprequest',
            name='day',
        ),
    ]
