# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0024_remove_workshoprequest_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='organization_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='presenter_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='workshop_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
