# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0026_ambassadorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
