# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0027_ambassadorrequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('workshop', 'البرنامج التدريبي'), ('presenter', 'المدرب'), ('organization', 'وحدة التدريب')], max_length=255)),
                ('workshop_met_expectations', models.IntegerField(default=0)),
                ('workshop_enough_duration', models.IntegerField(default=0)),
                ('workshop_content', models.IntegerField(default=0)),
                ('workshop_equipment_available', models.IntegerField(default=0)),
                ('workshop_recommend_friends', models.IntegerField(default=0)),
                ('presenter_on_time', models.IntegerField(default=0)),
                ('presenter_on_topic', models.IntegerField(default=0)),
                ('presenter_clear', models.IntegerField(default=0)),
                ('presenter_suggestions_exchange', models.IntegerField(default=0)),
                ('presenter_competent', models.IntegerField(default=0)),
                ('organization_room_prepared', models.IntegerField(default=0)),
                ('organization_organized', models.IntegerField(default=0)),
                ('organization_cooperative', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.ThinkingEnvUser')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.Workshop')),
            ],
        ),
    ]
