# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0033_thinkingenvuser_forgot_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinkingenvuser',
            name='created_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thinkingenvuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'متزوج'), ('single', 'أعزب')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thinkingenvuser',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('user', 'مستخدم'), ('expert', 'خبير')], default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='thinkingenvuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=255, null=True),
        ),
    ]
