# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0035_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
