# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0036_auto_20170510_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorExtraRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambassador_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.AmbassadorCity')),
            ],
        ),
        migrations.AddField(
            model_name='ambassadorcity',
            name='ambassador_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tems.AmbassadorCountry'),
        ),
    ]
