# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 15:22
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0037_auto_20170906_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographic',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='infographics/'),
        ),
    ]
