# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 15:30
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0038_infographic_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infographic',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='infographic',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='infographics/'),
        ),
    ]
