# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0039_auto_20170911_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinkingenvuser',
            name='booklet_download_count',
            field=models.IntegerField(default=0),
        ),
    ]
