# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0041_book_main_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='training_guide',
            field=models.BooleanField(default=False),
        ),
    ]
