# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0042_book_training_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorrequest',
            name='about_you',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ambassadorrequest',
            name='what_can_you_provide',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.TextField(),
        ),
    ]
