# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tems', '0043_auto_20180226_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorcountry',
            name='flag',
            field=models.ImageField(null=True, upload_to='countries/'),
        ),
    ]
